/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/declarations.d`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/playerManager` | `/playerManager`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/players` | `/players`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/PlayerManager`; params?: Router.UnknownInputParams; } | { pathname: `/screens/PlayersScreen`; params?: Router.UnknownInputParams; } | { pathname: `/types/Countries`; params?: Router.UnknownInputParams; } | { pathname: `/types/Match`; params?: Router.UnknownInputParams; } | { pathname: `/types/Player`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/declarations.d`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/playerManager` | `/playerManager`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/players` | `/players`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/PlayerManager`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/PlayersScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/types/Countries`; params?: Router.UnknownOutputParams; } | { pathname: `/types/Match`; params?: Router.UnknownOutputParams; } | { pathname: `/types/Player`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/declarations.d${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/playerManager${`?${string}` | `#${string}` | ''}` | `/playerManager${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/players${`?${string}` | `#${string}` | ''}` | `/players${`?${string}` | `#${string}` | ''}` | `/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/PlayerManager${`?${string}` | `#${string}` | ''}` | `/screens/PlayersScreen${`?${string}` | `#${string}` | ''}` | `/types/Countries${`?${string}` | `#${string}` | ''}` | `/types/Match${`?${string}` | `#${string}` | ''}` | `/types/Player${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/declarations.d`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/playerManager` | `/playerManager`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/players` | `/players`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/PlayerManager`; params?: Router.UnknownInputParams; } | { pathname: `/screens/PlayersScreen`; params?: Router.UnknownInputParams; } | { pathname: `/types/Countries`; params?: Router.UnknownInputParams; } | { pathname: `/types/Match`; params?: Router.UnknownInputParams; } | { pathname: `/types/Player`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
